### PR TITLE
The next web responsive design

### PR DESCRIPTION
**Pull request by JohnHernCode**
Project progress and milestones met:
1. Created the skeleton for the mobile site
2. Created the media queries for responsiveness
3. Added content and media to the site

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @JohnHernandez-code and @Nasa28  . Thanks for submitting you project!

Great thing this project has and has done well:
:100: Great solid start!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] One of the Requirements is to create a professional repository. The README is missing:
   - Screenshot of the project
   - An image in the MIT license is broken
   - A working Live Preview of the project, you can use Netlify, GitHub Pages, or RawGitHack.
  - The README mentions the issue page, but there is no link to it.

- [ ] Please remove the files that are not necessary. The project only uses one Font, all unused font files should be removed.

- [x] `<header>` is a principal HTML tag, it should be used outside `<main>`.
```
<header>
  <nav></nav>
</header>

<main>
  ... some code...
</main>

<footer>
  ... some code...
</footer>
```

- [x] `<nav>` should be wrapped around the `<header>` tag.

- [ ] **Navigation bar**
Large version
- [ ] It contains main navigation row 
- [ ] It contains sub-navigation row 
- [ ] It contains search icon at the rightmost side of sub-navigation row 


- [ ] **Top 3 articles section**
- [ ] It contains 3 articles with an image as a **background** 
Large version
- [ ] It contains one bigger image on the leftmost part of the row 
- [ ] It contains two smaller images on the rightmost part of the row 
- [ ] It contains TWN logo at the top left corner of the row 
Medium version changes
- [ ] TWN logo disappears 
Small version changes

- [ ] **Latest news section**
- [ ] The information should not be the same as the latest deals, this sections doesn't use prices.
Medium version changes
- [ ] It aligns 3 articles per row 

- [ ] Latest Funding section
Medium version changes
- [ ] It aligns 3 articles per row 
Small version changes
- [ ] there should be only 3 articles

- [ ] Categories  section
Medium version changes
- [ ] It aligns 2 category boxes per row 

- [ ] Latest deals section
Medium version changes
- [ ] It aligns 3 deals per row 


- [ ] Website is not fully responsive, is missing tablet view, is not changing, hiding and moving elements as original website. Please use the media query inspector to observe the changes in the original website and try to mimic that in the project.

- [ ] Visual observations
image
- 1 navbar is not looking as the original website
- 2 desktop version is missing the TNW logo
- 3 The background image looks distorted, is smaller than the container, and is repeated, use `background-position: cover` css rule to fix it.
- 4, 5, and 6 Titles are missing, or have small text.

- [ ] latest news title mismatch the color
image

- [ ] Latest news is not aligned to the center

- [ ] Images are not showing
image

- [ ] This is how it looks on tablet view 768px width
image
image

- [ ] If the page is messed up in the browser or in GitHack check if the paths of the CSS files and/or images and other assets are written correctly:
```
// Bad Paths
<link rel="stylesheet" href="/assets/stylesheets/main.css">
<link rel="stylesheet" href="/assets/js/bootstrap.min.js">
<img src="/imgs/myimage.png">


// Good Paths
<link rel="stylesheet" href="./assets/stylesheets/main.css">
<link rel="stylesheet" href="./assets/js/bootstrap.min.js">
<img src="./imgs/myimage.png">

```
  - notice how the correct paths start with a `./` that marks the current position of the file within the project directory. Without that the browser wont know where the path to the asset should start from.

- [ ] Keep the CSS file Dry, by creating helper CSS selectors or grouping elements that share common CSS rules. Example:
```css
.position-relative {
  position: relative;
}

/* -- OR -- */

.header,
.main,
.footer,
.navbar a {
  position: relative;
}
```

### [OPTIONAL]  :yellow_circle:  

- [ ] The github information about the authors could be better if they where actual links instead of text in code blocks. Example:

**GitHub:** [@jubaan](https://www.github.com/jubaan) this is done like `[@jubaan](https://www.github.com/jubaan)`


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by JohnHernCode** [comment]
> 
> # Status: Changes Required ♻️
> ## 👋 👋 Hello @JohnHernandez-code and @Nasa28 . Thanks for submitting you project!
> 
> Great thing this project has and has done well:
> 💯 Great solid start!
> 
> There are some issues that need to be addressed before we can move forward. Please review the list below.
> ## Required changes 🔧
> ### [Mandatory] 🔴
> 
>     * [ ]  One of the Requirements is to create a professional repository. The README is missing:
>       
>       * Screenshot of the project
>       * An image in the MIT license is broken
>       * A working Live Preview of the project, you can use Netlify, GitHub Pages, or RawGitHack.
>       * The README mentions the issue page, but there is no link to it.
> 
>     * [ ]  Please remove the files that are not necessary. The project only uses one Font, all unused font files should be removed.
> 
>     * [ ]  `<header>` is a principal HTML tag, it should be used outside `<main>`.
> 
> 
> ```
> <header>
>   <nav></nav>
> </header>
> 
> <main>
>   ... some code...
> </main>
> 
> <footer>
>   ... some code...
> </footer>
> ```
> 
>     * [ ]  `<nav>` should be wrapped around the `<header>` tag.
> 
>     * [ ]  **Navigation bar**
>       Large version
> 
>     * [ ]  It contains main navigation row
> 
>     * [ ]  It contains sub-navigation row
> 
>     * [ ]  It contains search icon at the rightmost side of sub-navigation row
> 
>     * [ ]  **Top 3 articles section**
> 
>     * [ ]  It contains 3 articles with an image as a **background**
>       Large version
> 
>     * [ ]  It contains one bigger image on the leftmost part of the row
> 
>     * [ ]  It contains two smaller images on the rightmost part of the row
> 
>     * [ ]  It contains TWN logo at the top left corner of the row
>       Medium version changes
> 
>     * [ ]  TWN logo disappears
>       Small version changes
> 
>     * [ ]  **Latest news section**
> 
>     * [ ]  The information should not be the same as the latest deals, this sections doesn't use prices.
>       Medium version changes
> 
>     * [ ]  It aligns 3 articles per row
> 
>     * [ ]  Latest Funding section
>       Medium version changes
> 
>     * [ ]  It aligns 3 articles per row
>       Small version changes
> 
>     * [ ]  there should be only 3 articles
> 
>     * [ ]  Categories  section
>       Medium version changes
> 
>     * [ ]  It aligns 2 category boxes per row
> 
>     * [ ]  Latest deals section
>       Medium version changes
> 
>     * [ ]  It aligns 3 deals per row
> 
>     * [ ]  Website is not fully responsive, is missing tablet view, is not changing, hiding and moving elements as original website. Please use the media query inspector to observe the changes in the original website and try to mimic that in the project.
> 
>     * [ ]  Visual observations
>       image
> 
>     * 1 navbar is not looking as the original website
> 
>     * 2 desktop version is missing the TNW logo
> 
>     * 3 The background image looks distorted, is smaller than the container, and is repeated, use `background-position: cover` css rule to fix it.
> 
>     * 4, 5, and 6 Titles are missing, or have small text.
> 
>     * [ ]  latest news title mismatch the color
>       image
> 
>     * [ ]  Latest news is not aligned to the center
> 
>     * [ ]  Images are not showing
>       image
> 
>     * [ ]  This is how it looks on tablet view 768px width
>       image
>       image
> 
>     * [ ]  If the page is messed up in the browser or in GitHack check if the paths of the CSS files and/or images and other assets are written correctly:
> 
> 
> ```
> // Bad Paths
> <link rel="stylesheet" href="/assets/stylesheets/main.css">
> <link rel="stylesheet" href="/assets/js/bootstrap.min.js">
> 
> 
> 
> // Good Paths
> <link rel="stylesheet" href="./assets/stylesheets/main.css">
> <link rel="stylesheet" href="./assets/js/bootstrap.min.js">
> 
> ```
> 
>     * notice how the correct paths start with a `./` that marks the current position of the file within the project directory. Without that the browser wont know where the path to the asset should start from.
> 
>     * [ ]  Keep the CSS file Dry, by creating helper CSS selectors or grouping elements that share common CSS rules. Example:
> 
> 
> ```css
> .position-relative {
>   position: relative;
> }
> 
> /* -- OR -- */
> 
> .header,
> .main,
> .footer,
> .navbar a {
>   position: relative;
> }
> ```
> 
> ### [OPTIONAL] 🟡
> 
>     * [ ]  The github information about the authors could be better if they where actual links instead of text in code blocks. Example:
> 
> 
> **GitHub:** [@jubaan](https://www.github.com/jubaan) this is done like `[@jubaan](https://www.github.com/jubaan)`
> ## Keep up the great work 💪 and Happy Coding 😃 💻!!

Hi there, we appreciate the code review and will work on it promptly. Unfortunately, following "linters" has broken some css (e.g. this belongs higher than that), and so a bunch of stuff doesn't work like it did before we followed linters. 

We will be working on it to fix the issues and solve this promptly.

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️

Hi, team @JohnHernandez-code and @Nasa28 👋 👋 , good job on working on the feedback given by the previous TSE. Your project looks good but let's make it even better by doing the following:

- [x]  The README file still needs a little more work to be done. You can clone this [template](https://github.com/microverseinc/readme-template) and edit it with all the relevant information.

- [ ] Check on your stylelint errors, you can take advantage of `npx stylelint --fix` to help fix some errors.

#### Navigation bar

- [x] Check on the styling of the navbar. You can reduce the margin between each element. Let's make it look like the original one. ([link to page](https://thenextweb.com/))
**Original**
o
**Clone**
c

#### Top 3 articles section
##### Large Version

- [x] The TNW logo is losing its pixels, kindly check on that.  ([link to page](https://thenextweb.com/))
c

##### Latest news section

###### Large version

- [x] Reduce the margin between each article to make it look like the original page. ([link to page](https://thenextweb.com/))
**Original**
o
**Clone**
c

###### Medium version changes

* [x] It aligns 3 articles per row ([link to page](https://thenextweb.com/))

###### Small version changes
* [x] The images are stretched out in this version. Check on the width and height of the images. ([link to page](https://thenextweb.com/))
* [x] The font size is big for the view, kindly reduce the font size to make it look better. ([link to page](https://thenextweb.com/))
**Original**
o
**Clone**
c

##### Latest Funding section

###### Large version

* [x] This part is missing on the large version. Kindly add it.  ([link to page](https://thenextweb.com/))
* [x] It should contain a header with the section name ([link to page](https://thenextweb.com/))
* [x] It aligns 4 articles per row ([link to page](https://thenextweb.com/))

###### Medium version changes
* [x] This part is also missing on the medium version. Kindly add it.  ([link to page](https://thenextweb.com/))
* [x] It aligns 3 articles per row ([link to page](https://thenextweb.com/))

##### Latest deals section

###### Large version
- [x] Reduce the margin between each article to make it look like the original page. ([link to page](https://thenextweb.com/))

**Clone**
c

###### Medium version changes

* [x] It aligns 3 deals per row ([link to page](https://thenextweb.com/))

###### Small version changes
* [x] The images are stretched out in this version. Check on the width and height of the images. ([link to page](https://thenextweb.com/))
* [x] The font size is big for the view, kindly reduce the font size to make it look better. ([link to page](https://thenextweb.com/))

**Clone**
c

##### Footer

* [x] Let's make it look like the original page. You can add more margins and padding between the social media icons and the text below it. Check out the screenshot below to check the difference

**Original**
o


**Clone**
c

Thats all 😄 , kindy work on the review and submit another form when you are done 🙏 

Regards
Peris Ndanu
If you have any questions kindly slack me anytime.

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hey, team @JohnHernandez-code and @Nasa28 you guys did a great job on this project. It looks similar to the original page.
I really wanted to approve this project but I noticed something that you need to fix

- [x] There are some stylelint errors that can be easily fixed if you run `npx stylelint --fix`. Check out this [link ](https://github.com/microverseinc/linters-config/tree/master/html-css)for the configurations

- [x] Add more social media links for the first Author on the README file

- [x] Add the `Usage` section on your README. This section includes instructions a user needs to follow to use your project on localhost. Check out this [link](https://github.com/microverseinc/readme-template) to get inspiration 😉 


That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
Feel free to reach out on slack if you have any questions

**Comment by JohnHernCode** [comment]
> ### STATUS: CHANGES REQUESTED 🔴 ♻️
> 
> Hey, team @JohnHernandez-code and @Nasa28 you guys did a great job on this project. It looks similar to the original page.
> I really wanted to approve this project but I noticed something that you need to fix
> 
>     * [x]  There are some stylelint errors that can be easily fixed if you run `npx stylelint --fix`. Check out this [link ](https://github.com/microverseinc/linters-config/tree/master/html-css)for the configurations
> 
>     * [x]  Add more social media links for the first Author on the README file
> 
>     * [x]  Add the `Usage` section on your README. This section includes instructions a user needs to follow to use your project on localhost. Check out this [link](https://github.com/microverseinc/readme-template) to get inspiration 😉
> 
> 
> That's all. 😄 , kindy submit another review when you are done
> 
> Regards
> Peris Ndanu
> Feel free to reach out on slack if you have any questions

Hi, 

The final changes have been made. I appreciate your feedback.

**Comment by mimipeshy** [comment]
### STATUS :APPROVED 🥳  💯 
Hey team @JohnHernandez-code and @Nasa28, you guys did so well in this project. You worked on all feedback given, I, therefore, approve this project. Go ahead and merge 👍  All the best in the future projects

Regards
Peris Ndanu

**Pull request merged**
